server:
  port: 5454

# db specific properties
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  # ORM s/w specific properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: sharma.sanjay2054@gmail.com
    password: twxcerfmlbtydnky
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
